# Generated by Django 5.0.1 on 2026-04-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_submission_unique_together_submission_content_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submission',
            table='students_submission',
        ),
    ]
