# Generated by Django 5.0.1 on 2026-05-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teachersalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
