# Generated by Django 5.0.1 on 2026-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_grade_submission_marks_remove_course_teachers_and_more'),
        ('teachers', '0005_remove_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='courses.course'),
        ),
    ]
