# Generated by Django 5.0.1 on 2026-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='total_leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
