# Generated by Django 5.0.1 on 2026-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_holiday_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
