# Generated by Django 5.0.1 on 2026-06-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_assignment_attachment'),
        ('notices', '0001_initial'),
        ('teachers', '0009_holiday_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_admin_notice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
