# Generated by Django 5.0.1 on 2026-03-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_courseprogress_note_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseProgress',
        ),
    ]
