# Generated by Django 5.0.1 on 2026-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_assignment_deadline_remove_assignment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
