# Generated by Django 5.0.1 on 2026-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_assignment_is_completed_and_more'),
        ('teachers', '0005_remove_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='teachers.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
