# Generated by Django 5.0.1 on 2026-05-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teachers_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='marks',
            new_name='grade',
        ),
    ]
