# Generated by Django 5.0.1 on 2026-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_marks_submission_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='grade',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='courses.course')),
            ],
        ),
    ]
