# Generated by Django 5.0.1 on 2026-05-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_grade_submission_marks_remove_course_teachers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='marks',
            new_name='grade',
        ),
    ]
