# Generated by Django 5.0.1 on 2026-07-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_assignment_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
