# Generated by Django 5.0.1 on 2026-07-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_delete_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
