# Generated by Django 5.0.1 on 2026-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('broadcast', 'Broadcast')], default='personal', max_length=20),
        ),
    ]
